# Generated by Django 6.0.7 on 2026-08-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productvariant_discount_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_end',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_start',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
