# Generated by Django 6.0.7 on 2026-08-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_productvariant_discount_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
