# Generated by Django 6.0.7 on 2026-08-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productvariant_discount_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashsale',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_start',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_end',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_start',
        ),
        migrations.AddField(
            model_name='flashsale',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='flash_sales', to='shop.product'),
        ),
    ]
