# Generated by Django 6.0.7 on 2026-08-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_discount',
            field=models.IntegerField(default=0),
        ),
    ]
