# Generated by Django 6.0.7 on 2026-08-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_stocknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price you paid to acquire/manufacture this product — used to calculate profit', max_digits=10),
        ),
    ]
