# Generated by Django 6.0.7 on 2026-08-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, help_text="Which color this photo shows (must match a variant's color exactly, e.g. 'Black'). Leave empty for a general/default photo.", max_length=30),
        ),
    ]
