# Generated by Django 6.0.7 on 2026-08-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_address_phone_alter_productvariant_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('in', 'Inches'), ('cm', 'Centimeters')], default='in', max_length=5)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='size_chart', to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='SizeChartRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('chest', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('hip', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('size_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='shop.sizechart')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('size_chart', 'size')},
            },
        ),
    ]
