# Generated by Django 6.0.7 on 2026-08-08 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_sizechart_sizechartrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizechart',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_chart', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='sizechart',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_chart', to='shop.category'),
        ),
    ]
