# Generated by Django 6.0.7 on 2026-08-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
