# Generated by Django 6.0.7 on 2026-08-09 16:47
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def generate_unique_tokens(apps, schema_editor):
    Order = apps.get_model('shop', 'Order')
    for order in Order.objects.all():
        order.public_token = uuid.uuid4()
        order.save(update_fields=['public_token'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0019_coupon_times_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        # Step 1: add public_token as NON-unique, nullable first — this avoids
        # SQLite trying to write the same default value into every existing row.
        migrations.AddField(
            model_name='order',
            name='public_token',
            field=models.UUIDField(null=True, editable=False),
        ),
        # Step 2: populate a distinct uuid4 for every existing row.
        migrations.RunPython(generate_unique_tokens, reverse_noop),
        # Step 3: now that every row has a distinct value, enforce uniqueness.
        migrations.AlterField(
            model_name='order',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]