# Generated by Django 6.0.7 on 2026-08-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_order_guest_address_order_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizechartrow',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
