# Generated by Django 6.0.7 on 2026-08-10 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_meta_description_product_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wishlist_share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
