# Generated by Django 6.0.7 on 2026-08-15 15:11

import uuid

from django.db import migrations, models


def populate_wishlist_tokens(apps, schema_editor):
    UserProfile = apps.get_model('shop', 'UserProfile')
    seen = set()
    for profile in UserProfile.objects.all():
        token = profile.wishlist_share_token
        if not token or token in seen:
            new_token = uuid.uuid4().hex
            while new_token in seen:
                new_token = uuid.uuid4().hex
            profile.wishlist_share_token = new_token
            profile.save(update_fields=['wishlist_share_token'])
            seen.add(new_token)
        else:
            seen.add(token)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_category_meta_description_category_meta_title'),
    ]

    operations = [
        migrations.RunPython(populate_wishlist_tokens, reverse_noop),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]