# Generated by Django 6.0.7 on 2026-08-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Optional. Portrait/compact crop for mobile devices. If empty, the main "image" is used as fallback.', null=True, upload_to='banners/mobile/'),
        ),
    ]
